### ISSUE TITLE
Hen freezing

### ISSUE THREAD

**Issue by BeemerDream** [PS3-4K-Pro/PS3-4K-Pro#15]
Hi! Installed PS3 Pro lite on HFW 4.91, Hen 3.3.0 and Webman mod (latest, 1.47.47 I think), but when I'm enabling Hen the PS3 freezes. Emergency jailbreak works, but then Webman mod is disabled.
When I uninstall PS3 Pro it doesn't freeze and Webman is working just fine.

**Comment by LuanTeles** [comment]
That's wierd, did you try to delete your webMAN config file? (/dev_hdd0/tmp/wm_config.bin)

**Comment by Damyyxz47** [comment]
I also have the same issue

**Comment by Damyyxz47** [comment]
For me when im enabling HEN it says its enabled but it just keeps loading, and if i try to close my system it freezes and i have to pull the plug, any fixes?

**Comment by LuanTeles** [comment]
> For me when im enabling HEN it says its enabled but it just keeps loading, and if i try to close my system it freezes and i have to pull the plug, any fixes?

Are you using SSD?

**Comment by Damyyxz47** [comment]
> > For me when im enabling HEN it says its enabled but it just keeps loading, and if i try to close my system it freezes and i have to pull the plug, any fixes?
> 
> Are you using SSD?

Yea
