### ISSUE TITLE
PS3 Bricked

### ISSUE THREAD

**Issue by matissime** [PS3-4K-Pro/PS3-4K-Pro#2]
Hello, when changing the PS3 4k Theme, there was a power outage, and now my PS3 is not able to start, and the whole system became bricked, I can't restore the file system, can't apply updates over USB, the recovery mode isn't working, nothing is working. And it went into weird graphic issues, like when the PS3 is playing system sound effect when selecting an item in a menu, i do a loud weird noise sound and the loading bar items is looking like big white rectangle. Any ideas how I can unbrick my system ? If there is someone with PS3 knowleges and unbricking experiences I can pay him if he sucessfully unbrick my system.

**Comment by LuanTeles** [comment]
Take out your hdd , connect into a PC and format it

**Comment by matissime** [comment]
Already did that, but I sucessfully manage to unbrick the PS3 by flashing the firmware with the appropriate one which was : REBUG_CFW_v4.84.2 so the learned lesson is to always keep a backup of the file and firmware used to jailbreak your console as if you don't remember which version you had installed, it will be complicated, and in my case I was lucky to find the right version.
