### ISSUE TITLE
Glitch icons

### ISSUE THREAD

**Issue by Letsplay1108** [PS3-4K-Pro/PS3-4K-Pro#4]
![image](https://user-images.githubusercontent.com/82605931/220652850-8edcd6f8-a60f-4128-a204-40e857af7fda.png)
Why is this happening?

**Comment by THerianQ** [comment]
Happens to me too

**Comment by LuanTeles** [comment]
> Happens to me too

On firmwares 4.89+ sony changed the layout.txt files to add the QR codes, all mods needs to be remake, i solved it by patching the layout file but it is not perfect.

It is available on v5.3 and v5.4 version of the mod, using older releases will have this issue.
